---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "90"
  name: pre-sync-cp4d-cluster-setup
  namespace: {{.Values.metadata.argocd_namespace}}
spec:
  template:
    spec:
      containers:
        - name: configure-cluster
          image: "icr.io/cpopen/cpd/olm-utils-v2:{{.Values.version}}{{.Values.image_arch}}"
          env:
            - name: PROJECT_CERT_MANAGER
              value: ibm-cert-manager
            - name: PROJECT_LICENSE_SERVICE
              value: ibm-licensing
            - name: PROJECT_SCHEDULING_SERVICE
              value: ibm-cpd-scheduler
            - name: VERSION
              value: {{.Values.version}}
            - name: COMPONENTS
              value: {{.Values.components}}
          command:
            - /bin/bash
            - -c
            - |
              set -eo pipefail
              set -x
              # (Your script remains unchanged)
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
            runAsNonRoot: true
            runAsUser: 1000 # Ensure a non-root UID is chosen
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      serviceAccountName: {{.Values.serviceaccount.argocd_application_controller}}
  backoffLimit: 1

